name: Pandoc Test

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 #Get the Guide repo
      - uses: docker://pandoc/latex:2.9 #Use LaTeX version of pandoc for pdf conversion
        with:
          args: >-
            --standalone
            --output=./guide.pdf
            --variable urlcolor=cyan
            ./guide.md
