name: Pandoc Test

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            ../../guide.md
            --standalone
            --output=../../guide.pdf
            --variable urlcolor=cyan
