name: Pandoc Test

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: pwd
      - run: ls -al
      - run: ls -al ../
      - run: ls -al ../../
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --standalone
            --output=./guide.pdf
            --variable urlcolor=cyan
            ./guide.md
